apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: street-db
  template:
    metadata:
      labels:
        app: street-db
    spec:
      containers:

        - name: street-db
          image: postgis/postgis
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: postgis-data
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgres-persistent-pvc