apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: street-db
  template:
    metadata:
      labels:
        app: street-db
    spec:
      containers:

        - name: street-db
          image: postgis/postgis
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: postgis-data
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgres-persistent-pvc

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: street-db
data:
  POSTGRES_DB: StreetDb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  HOST: "postgresnetdb.default"
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: street-db
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
  
---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: street-db
spec:
  ports:
    - port: 5432
  selector:
    app: street-db
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi